name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        continue-on-error: true
        run: |
          gh api repos/$GITHUB_REPOSITORY/actions/runs \
          --paginate -q '.workflow_runs[] | select(.head_branch != "master") | "\(.id)"' | \
          xargs -n1 -I % gh api repos/$GITHUB_REPOSITORY/actions/runs/% -X DELETE --silent
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}          
