name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: gh api repos/$user/$repo/actions/runs \ --paginate -q '.workflow_runs[] | select(.head_branch != "main") | "\(.id)"' | \ xargs -n1 -I % gh api repos/$GITHUB_REPOSITORY/actions/runs/% -X DELETE
