name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: |
          gh api repos/$GITHUB_REPOSITORY/actions/runs \
          | jq -r '.workflow_runs[] | select(.head_branch != "master") | "\(.id)"' \
          | xargs -n1 -J % gh api repos/$GITHUB_REPOSITORY/actions/runs/% -X DELETE
